### ISSUE TITLE
Update docs with various package installation instructions

### ISSUE THREAD

**Issue by Kadiza123** [pacificclimate/climdex.pcic#27]
Please how do I install climdex.pcic package? I have just installed climpact in R and when I runApp I got this message
_**Error in library(climdex.pcic) : 
  there is no package called ‘climdex.pcic’**_
I tried
 **_install.packages('climdex.pcic')_** but i get this Warning in install.packages :
  package ‘climdex.pcic’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by miturbide** [comment]
This points to an installation issue with the pacificclimate package climdex.pcic, which is a dependency of climate4R.climdex. Try installing this package first. climdex.pcic is no longer available on CRAN, so you can try installing it from GitHub as follows:

devtools::install_github("pacificclimate/climdex.pcic")

**Comment by miturbide** [comment]
devtools::install_github("pacificclimate/climdex.pcic")

**Comment by jameshiebert** [comment]
Unfortunately, CRAN removed the `climdex.pcic` package very shortly after a unit tests failed on one of the CRAN member's personal workstations. He had just performed an OS software update on MacOS. We at PCIC were given minimal notice, no opportunity to reproduce the problem, and our request for an extension was denied by CRAN. Re-submission of the package has been stymied by CRAN deleting the log files from the failing test that was run on the CRAN admin's personal workstation.

Like @miturbide mentioned, one can install `climdex.pcic` using the `devtools` package:

```R
# if devtools is not installed
install.packages('devtools')

devtools::install_github("pacificclimate/climdex.pcic")
```

Or using a source tarball. 
[climdex.pcic_1.1-11.tar.gz](https://github.com/pacificclimate/climdex.pcic/files/12099174/climdex.pcic_1.1-11.tar.gz)

```R
# ensure dependency is installed
install.packages('PCICt')

install.packages('/path/to/climdex.pcic_1.1-11.tar.gz')
# or
install.packages('https://github.com/pacificclimate/climdex.pcic/files/12099174/climdex.pcic_1.1-11.tar.gz')
```

We'll get the official version `1.1-11` of `climdex.pcic` on our website ASAP, and will update the documentation accordingly.
