### ISSUE TITLE
`nday.consec.prec.max()` fails for even `ndays`

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/climdex.pcic#4]
From @heroldn

The [`nday.consec.prec.max()`](https://github.com/pacificclimate/climdex.pcic/blob/master/R/climdex.r#L1674) function seems to only handle odd numbers for the parameter `ndays`. When I try even numbers I get an error "arguments must have same length". Looking at the function I can only imagine it's talking about the last return line which uses `tapply.fast`. Perhaps the padded data in `new.series` are a different length to date.factor, but then I can't imagine why it would only complain on even numbers.

**Comment by jameshiebert** [comment]
@heroldn It looks like there's an off-by-one "difference" (I originally wrote "error", but it's not *really* and error) in David's running[operation] algorithm. Look at where the computation takes place for the padding for the beginning and end of the series:

```R
new.series <- c(rep(0, floor(ndays / 2)), daily.prec, rep(0, floor(ndays / 2)))
```

A running sum or mean, at element `i` is defined as the mean of the `k` elements surrounding `i`. I.e. `mean(i-2, i-1, i, i+1, i+2)`. So it's the mean of the midpoint of the window which is `i` and `floor(k/2)` elements on either side.

For example, take the running sum of `c(1, 2, 3, 4, 5)` with a window of 3. The series gets padded out to `c(0, 0, 1, 2, 3, 4, 5, 0, 0)` and then computed iteratively to become `c(6, 10, 15, 14, 12)`. 

But what's the midpoint of an even length widow? I'd argue that it's undefined. As shown above (and as you've discovered) the code isn't even written to handle that case.

So what ends up happening is that the running sum or mean of a series over an even window doesn't  return a series of the same length... it returns a series of length `n-1`. And then `tapply` fails.

Can I ask, is this a real use case? For resolution of this, I'd propose that we simply check for oddness/evenness and raise a descriptive error when `ndays` is even (e.g. "nday.consec.prec.max() is undefined for even length windows"), and document the function accordingly. Then at least it doesn't trip up the user.

**Comment by heroldn** [comment]
Hi James, thanks for that. I never ran across that problem. I checked how ncl does this (as an arbitrary reference) and they seem to move the center to the later element (so by 0.5) - see below for an example. But, I'm not so concerned about this and you're right I'll put in a descriptive error for the user. Regarding your question, I think people would consider this a real use case, at least in my opinion. Intuitively there should be nothing stopping someone getting a 4 day running sum for example. But again, for our purposes I don't think it's a big deal.

https://www.ncl.ucar.edu/Document/Functions/Built-in/runave.shtml

i.e. with no cyclic boundary conditions;
> print(p)
(0)	1
(1)	2
(2)	3
(3)	4
(4)	5
> print(runave(p,3,0)) 
(0)	9.96921e+36
(1)	 2
(2)	 3
(3)	 4
(4)	9.96921e+36
> print(runave(p,2,0)) 
(0)	1.5
(1)	2.5
(2)	3.5
(3)	4.5
(4)	9.96921e+36
