### ISSUE TITLE
Write better docs for the behaviour of `max.missing.days` thresholds

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/climdex.pcic#5]
The `max.missing.days` parameter is a named vector ('monthly', 'annual') which controls how many missing values in a timeseries will invalidate a time range. The docs don't make it clear that invalidating a month will also invalidate the *whole year* for annual indices. Fix this in the docs.

**Comment by bronaugh** [comment]
Hi James,

One note on this: I'm not sure that RClimdex and FClimdex produce exactly
the same results here when it comes to missing values. It might be worth
verifying that before making these changes.

Frankly, I don't think we care if RClimdex produces different results, if
we are in line with FClimdex. Majority rules.

David

**Comment by jameshiebert** [comment]
Yeah, I don't expect that different Climdex implementations will necessarily behave exactly the same in all circumstances. In the face of arbitrary input, the definition of the ETCCDI indices aren't always unambiguous and implementing them involves making judgement calls.

The question arose with respect to the Summer Days index (days in a year > 25 C). Since Summer Days is an index defined as a count of the number of days over the course of the year, it wouldn't make sense to report this annual count if not all of the months were actually being included. For example, what if July had 11 missing values and is considered invalid? Invalidating July, and reporting "summer days" for the remainder of the year would be presumably report an articially low number (in the northern hemisphere).

I would contend that an annual index computed with only a subset of the months is invalid for that year and should be NA. And that's what `climdex.pcic` does.

**Comment by bronaugh** [comment]
namasks <- list(annual=lapply(filled.list, get.na.mask,
date.factors$annual, max.missing.days['annual']),
monthly=lapply(filled.list, get.na.mask, date.factors$monthly,
max.missing.days['monthly']))
  namasks$annual <- lapply(names(namasks$annual), function(v) { d <-
namasks$annual[[v]] * as.numeric(tapply(namasks$monthly[[v]],
rep(seq_along(namasks$annual[[v]]), each=12), prod)); dimnames(d) <-
dim(d) <- NULL; d })

We made a deliberate decision (I believe this follows fclimdex's
behaviour) that if any month was missing (as per the max.missing.days
parameter), that the annual data should be missing.

Unfortunately I can't refer to the fclimdex.f code, because it's
behind an auth wall (who made that decision?).

David

**Comment by jameshiebert** [comment]
Yep, I agree with that decision. This issue is just to remind me to explain this in the docs so that users understand this as well.

**Comment by bronaugh** [comment]
I think that's already covered in the docs:

#' The \code{max.missing.days} argument is a vector consisting of 'annual'
#' (the number of days that can be missing in a year) and 'monthly' (the
#' number of days that can be missing in a month. If one month in a year fails
#' the test, the corresponding year will be omitted.

This is from the docs for climdexInput.raw. So perhaps this is just a
matter of making sure this is in multiple places.

David

**Comment by jameshiebert** [comment]
Ah, I missed that... thanks for the pointer! Though, as it turns out, that paragraph in question doesn't actually make it into the compiled docs because there's a `roxygen2` formatting bug. To use multi-paragraph blocks, you apparently have to explicitly declare the blocks. That's a separate issue that I'll report and fix before the next release.

**Comment by bronaugh** [comment]
Neato... didn't know about that!

**Comment by jameshiebert** [comment]
With the multi-paragraph docs fixed (so that you can actually *read* about how `max.missing.days` works), I think that the current docs do it justice. Closing this ticket.
